# %% [markdown]
# # Removal of Co, Li and PW metals by dolomite: a kinetic batch reaction model
#
# **Following Omar & Vilcáez (2024)**, *The role of alkalinity on metals removal from petroleum
# produced water by dolomite*, Applied Geochemistry 161, 105879 — the same group, the same
# apparatus, the same modelling strategy.
#
# ## Why this replaces the equilibrium-inversion approach
#
# The earlier analysis treated each sampling as an independent equilibrium point and inverted the
# mass action law at it. That is Belova's procedure for a true adsorption edge, and it fails here
# because these are **kinetic batch experiments**: pH, alkalinity and the Ca/Mg competitor load
# are *generated by dolomite dissolution during the run*, not imposed.
#
# Omar & Vilcáez model exactly this system and do it differently:
#
# | Step | Treatment |
# |---|---|
# | Dolomite dissolution | **kinetic**, transition state theory (Lasaga, 1984), their Eq. 2 |
# | Aqueous complexation | equilibrium, their Table 5 |
# | Carbonate mineral precipitation | equilibrium (instantaneous), their Table 6 |
# | Sorption | three dolomite hydration sites, K_int as their Eq. 1 |
# | Output | **concentration against time**, their Fig. 14 |
# | Mechanism split | run with precipitation only, then with sorption + precipitation |
#
# Crucially, on how they obtain the constants: *"K_int for Ca and Mg corresponds to measured
# values at low salinity (Pokrovsky et al., 1999), whereas **K_int for Sr, Cd, and Pb are assumed
# values based on observed removal levels**."* The constant is **calibrated so that the simulated
# concentration profile reproduces the measured one** — not inverted point by point. That is the
# procedure applied here to Co and Li.
#
# Their published values, which set the scale:
#
# | Metal | log K_int | removal in their PW |
# |---|---|---|
# | Cd | −0.233 | high |
# | Ca | −1.8 (Pokrovsky) | — |
# | Mg | −2.0 (Pokrovsky) | — |
# | Pb | −2.33 | high, mostly precipitation |
# | Sr | −4.66 | low |

# %%
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from scipy.optimize import brentq, minimize_scalar
import os
pd.set_option("display.width", 170); pd.set_option("display.precision", 4)
os.makedirs("figures", exist_ok=True)

def head(n, t): print(f"\n{'='*94}\n{n}  {t}\n{'='*94}")
def show(df): print(df.to_string(index=False, float_format=lambda x: f"{x:,.4g}"))

plt.rcParams.update({
    "font.family": "sans-serif", "font.sans-serif": ["DejaVu Sans", "Arial"],
    "font.size": 9, "axes.labelsize": 9.5, "legend.fontsize": 8,
    "figure.facecolor": "white", "axes.facecolor": "white", "savefig.facecolor": "white",
    "axes.grid": False, "axes.spines.top": True, "axes.spines.right": True,
    "axes.linewidth": 0.8, "xtick.direction": "in", "ytick.direction": "in",
    "xtick.top": True, "ytick.right": True, "xtick.minor.visible": True,
    "ytick.minor.visible": True, "lines.linewidth": 1.5, "lines.markersize": 6,
    "legend.frameon": False, "savefig.dpi": 300, "savefig.bbox": "tight", "pdf.fonttype": 42})

MCOL = {"Co": "#1f5f8b", "Li": "#c8542a", "Pb": "#4a4a4a", "Cd": "#e0a800",
        "Ba": "#7a5c99", "Sr": "#3a7d5d", "Ca": "#999999", "Mg": "#bbbbbb"}
def savefig(fig, name):
    fig.savefig(f"figures/{name}.png"); fig.savefig(f"figures/{name}.pdf"); plt.show()

# %% [markdown]
# ## 1 — Thermodynamic data
#
# Aqueous complexation from Omar & Vilcáez Table 5, mineral reactions from their Table 6, both
# written as dissociation constants exactly as they print them. Values for Co and the Li
# carbonate, which their study did not include, are taken from the same EQ3/EQ6 convention.

# %%
head(1, "Thermodynamic data (Omar & Vilcaez 2024, Tables 5 and 6)")

F, R_GAS, T_K = 96485.0, 8.314, 298.15
MM = dict(Ca=40.078, Mg=24.305, Na=22.990, Cl=35.453, Li=6.941, Co=58.933,
          Pb=207.2, Sr=87.62, Ba=137.33, Cd=112.41)

# --- Table 5: aqueous complexation, written as written in the paper -------------------------
LOGK_H2O   = -13.991        # OH- + H+ = H2O          (so Kw = 10^-13.991 the other way)
LOGK_CO2   = -6.342         # CO2(aq) + H2O = H+ + HCO3-
LOGK_CO3   = 10.325         # CO3-2 + H+ = HCO3-
LOGK_CO2G  = -7.809         # CO2(g) + H2O = H+ + HCO3-

# MeOH+ + H+ = Me2+ + H2O    (dissociation; larger = weaker hydroxide complex)
LOGK_MEOH = dict(Ca=12.852, Mg=11.790, Sr=13.290, Cd=10.075, Pb=7.695, Co=9.650, Ba=13.360)
# MeCO3(aq) + H+ = Me2+ + HCO3-
LOGK_MECO3 = dict(Ca=7.009, Mg=7.356, Sr=7.470, Cd=7.328, Pb=3.748, Co=6.100, Ba=7.700)
# MeCl+ = Me2+ + Cl-
LOGK_MECL = dict(Ca=0.701, Mg=0.139, Sr=0.253, Cd=-2.706, Pb=-1.432, Co=-0.300, Ba=0.500)

# --- Table 6: mineral reactions, MeCO3 + H+ = Me2+ + HCO3- ----------------------------------
LOGK_MIN = {"Dolomite": -0.7717, "Calcite": -0.8070, "Magnesite": -1.5934,
            "Strontianite": -0.7702, "Otavite": 1.2378, "Cerussite": 1.0681,
            "Witherite": -0.1130,            # BaCO3, EQ3/6
            "Sphaerocobaltite": 0.4200,      # CoCO3, EQ3/6 convention
            }
MIN_CATION = {"Calcite": "Ca", "Magnesite": "Mg", "Strontianite": "Sr", "Otavite": "Cd",
              "Cerussite": "Pb", "Witherite": "Ba", "Sphaerocobaltite": "Co"}

# --- sorption: three dolomite hydration sites (Pokrovsky et al. 1999) -----------------------
SITE_DENS = dict(CO3=14.0e-6, Ca=7.0e-6, Mg=7.0e-6)     # mol/m2
LOGK_CO3H = -4.8                                        # >CO3H0 = >CO3- + H+

# K_int = [>CO3Me+][H+] / ([>CO3H0][Me2+])    Omar & Vilcaez Eq. 1
# Ca and Mg measured (Pokrovsky 1999); Sr, Cd, Pb calibrated by Omar & Vilcaez to removal.
LOGK_INT = dict(Ca=-1.8, Mg=-2.0, Sr=-4.66, Cd=-0.233, Pb=-2.33)
# Co and Li are what this study determines, by the same calibration procedure.
LOGK_INT_FIT = dict(Co=None, Li=None, Ba=None)

show(pd.DataFrame([(k, v) for k, v in LOGK_INT.items()],
                  columns=["metal", "log K_int (Omar & Vilcaez 2024)"]))
print("\nCo, Li and Ba are calibrated below, by the same procedure the paper used for Sr, Cd, Pb.")

# %% [markdown]
# ## 2 — The two datasets
#
# Both are batch reactions, dolomite 6 g per 100 mL (60 g L⁻¹), 40 g L⁻¹ NaCl, 25 °C, sampled at
# days 0, 2, 4 and 6, with pH recorded at each sampling. The batch labels are **nominal initial**
# pH; the measured pH rises as dolomite dissolves, which is the point of the model.
#
# The contrast between the two is the whole reason the produced-water set is required.

# %%
head(2, "The two datasets")

# --- single ion: Co or Li alone in NaCl ------------------------------------------------------
SINGLE = pd.DataFrame([
    ("Co","pH6",0,   0.100,  0.100, 80.513, 6.320), ("Co","pH6",2,   0.100,  0.100, 77.905, 7.400),
    ("Co","pH6",4,   0.100,  8.143, 76.411, 7.477), ("Co","pH6",6,   0.126, 12.941, 74.393, 8.090),
    ("Co","pH2",0,   0.100,  0.100, 80.513, 2.350), ("Co","pH2",2,  57.477, 17.461, 79.661, 4.123),
    ("Co","pH2",4,  24.178, 45.592, 79.795, 5.660), ("Co","pH2",6,  21.658, 51.379, 80.398, 7.110),
    ("Li","pH6",0,   0.663,  0.100,138.430, 6.420), ("Li","pH6",2,  37.633,  0.100,134.657, 7.647),
    ("Li","pH6",4,  54.820,  0.100,136.722, 7.923), ("Li","pH6",6,  49.892,  0.870,135.262, 8.257),
    ("Li","pH2",0,   0.663,  0.100,138.430, 2.250), ("Li","pH2",2,  39.190,  0.100,136.263, 4.257),
    ("Li","pH2",4,  79.452, 21.316,135.956, 5.727), ("Li","pH2",6,  87.738, 20.547,135.592, 7.047),
], columns=["metal","batch","day","Ca_ppm","Mg_ppm","Me_ppm","pH"])
SINGLE["C0_ppm"]    = SINGLE.groupby(["metal","batch"]).Me_ppm.transform("first")
SINGLE["removal_%"] = 100*(SINGLE.C0_ppm - SINGLE.Me_ppm)/SINGLE.C0_ppm

# --- produced water: all metals together ------------------------------------------------------
PW_METALS = ["Pb", "Sr", "Ba", "Cd", "Co", "Li"]
PW = pd.DataFrame([
    ("pH6",0, 4185.950, 1005.970, 83.350, 88.579, 90.165, 92.673, 75.960, 76.780, 6.320),
    ("pH6",2, 3930.733,  940.894, 48.789, 82.369, 83.058, 84.949, 69.892, 71.243, 7.413),
    ("pH6",4, 3890.693,  984.050,  1.072, 82.500, 49.280, 25.739, 11.527, 71.470, 7.557),
    ("pH6",6, 3754.450,  967.633,  2.037, 83.166, 44.457, 14.066,  7.019, 70.212, 7.857),
    ("pH2",0, 4185.950, 1005.970, 83.350, 88.579, 90.165, 92.673, 75.960, 76.780, 2.350),
    ("pH2",2, 4037.933,  978.907, 47.138, 86.930, 87.731, 92.468, 75.013, 76.212, 4.290),
    ("pH2",4, 4199.987, 1115.780,  2.164, 86.297, 54.205, 43.352, 26.687, 74.399, 5.727),
], columns=["batch","day","Ca_ppm","Mg_ppm","Pb","Sr","Ba","Cd","Co","Li","pH"])
for m in PW_METALS:
    PW[m+"_rem"] = 100*(PW.groupby("batch")[m].transform("first") - PW[m]) \
                   / PW.groupby("batch")[m].transform("first")

print("SINGLE-ION batches (Co or Li alone in 40 g/L NaCl):")
show(SINGLE[["metal","batch","day","pH","Ca_ppm","Mg_ppm","Me_ppm","removal_%"]])
print("\nPRODUCED WATER batches (all metals together, high Ca and Mg from the start):")
show(PW[["batch","day","pH","Ca_ppm","Mg_ppm"] + PW_METALS])
print("\nRemoval in produced water, per cent of initial:")
show(PW[["batch","day","pH"] + [m+"_rem" for m in PW_METALS]])

print("\n" + "-"*94)
print("WHY THE PRODUCED-WATER SET IS THE ONE TO MODEL")
_s6 = SINGLE[(SINGLE.metal=="Co") & (SINGLE.batch=="pH6") & (SINGLE.day==6)]["removal_%"].iloc[0]
_p6 = PW[(PW.batch=="pH6") & (PW.day==6)]["Co_rem"].iloc[0]
print(f"  Cobalt removal at day 6:   single ion {_s6:.1f} %      produced water {_p6:.1f} %")
print(f"  With +/-3 % analytical precision, the relative error on the uptake is")
print(f"    single ion    ~{100*np.hypot(0.03*80.5, 0.03*74.4)/(80.5-74.4):.0f} %   - the signal and the noise are the same size")
print(f"    produced water ~{100*np.hypot(0.03*75.96, 0.03*7.02)/(75.96-7.02):.0f} %   - the uptake is 20 times its own error")
print("  The single-ion experiment cannot determine a constant; the produced-water experiment can.")
print("  The removal ORDER in PW - Pb > Co > Cd > Ba >> Li > Sr - is itself the calibration target,")
print("  and it is the same kind of target Omar & Vilcaez used to assign Sr, Cd and Pb.")
print("-"*94)

# %% [markdown]
# ## 3 — The model
#
# One well-mixed batch, integrated forward in time. At each step:
#
# 1. **Dolomite dissolves kinetically**, transition state theory (Lasaga, 1984; Omar & Vilcáez
#    Eq. 2), releasing Ca²⁺, Mg²⁺ and 2 HCO₃⁻ per mole and consuming 2 H⁺:
#
#    $$-R_{\mathrm{dol}} = A\,k_m\,[\mathrm{H^+}]\left\{1 -
#    \frac{[\mathrm{HCO_3^-}]^2[\mathrm{Ca^{2+}}][\mathrm{Mg^{2+}}]}{[\mathrm{H^+}]^2 K_{eq}}\right\}$$
#
# 2. **The solution re-equilibrates**: pH from charge balance, aqueous complexes from Table 5.
# 3. **Any supersaturated carbonate precipitates** to its solubility (instantaneous, Table 6).
# 4. **Sorption re-equilibrates** on the carbonate site, competitively across all cations.
#
# pH is an **output**, not an input. That is the central difference from the earlier treatment
# and the reason this reproduces a drifting batch rather than fighting it.

# %%
head(3, "The model")

DOL_GL, SSA = 60.0, 0.76                 # g/L and m2/g
S_AREA      = DOL_GL*SSA                 # 45.6 m2 per litre
S_T         = {k: v*S_AREA for k, v in SITE_DENS.items()}     # mol/L of suspension
K_M         = 3.0e-7                     # mol m-2 s-1, TST intrinsic rate constant (EQ3/6 range)

def gamma(I, z):
    """Davies activity coefficient."""
    f = -0.509*(np.sqrt(I)/(1 + np.sqrt(I)) - 0.3*I)
    return 10**(f*z*z)

def speciate(tot, CT, pH_guess=7.0):
    """Given total dissolved concentrations and total carbonate, solve pH from charge balance
    and return free-ion concentrations. tot carries Na, Cl and every divalent metal."""
    I = 0.5*(tot["Na"] + tot["Cl"] + sum(4*v for k, v in tot.items() if k not in ("Na", "Cl")))
    g1, g2 = gamma(I, 1), gamma(I, 2)

    def charge(pH):
        h = 10**(-pH)/g1
        oh = 10**(LOGK_H2O)/(10**(-pH))/g1
        # carbonate distribution over CT
        a_h = 10**(-pH)
        f_hco3 = 1.0
        f_co3  = 1.0/(10**LOGK_CO3*a_h)
        f_co2  = a_h/10**LOGK_CO2
        den = f_co2 + f_hco3 + f_co3
        hco3, co3 = CT*f_hco3/den, CT*f_co3/den
        pos = tot["Na"] + h
        for m, t in tot.items():
            if m in ("Na", "Cl"): continue
            z = 1 if m == "Li" else 2
            pos += z*t
        neg = tot["Cl"] + hco3 + 2*co3 + oh
        return pos - neg

    try:
        pH = brentq(charge, 1.0, 13.0, xtol=1e-8)
    except ValueError:
        pH = pH_guess
    a_h = 10**(-pH)
    f_hco3, f_co3, f_co2 = 1.0, 1.0/(10**LOGK_CO3*a_h), a_h/10**LOGK_CO2
    den = f_co2 + f_hco3 + f_co3
    return dict(pH=pH, I=I, g1=g1, g2=g2, a_h=a_h,
                HCO3=CT*f_hco3/den, CO3=CT*f_co3/den, CO2=CT*f_co2/den)

def free_fraction(metal, sp, tot):
    """Fraction of the dissolved metal present as the free ion, from the Table 5 complexes."""
    if metal == "Li": return 0.9
    d = 1.0
    d += tot["Cl"]/10**LOGK_MECL.get(metal, 0.0)                    # MeCl+
    d += sp["HCO3"]/10**LOGK_MECO3.get(metal, 7.0)/sp["a_h"]        # MeCO3(aq)
    d += 1.0/(10**LOGK_MEOH.get(metal, 12.0)*sp["a_h"])             # MeOH+
    return 1.0/d

def mineral_SI(metal, mineral, me_free, sp):
    """SI for MeCO3 + H+ = Me2+ + HCO3-, so IAP/K = (Me)(HCO3)/((H)(K))."""
    iap = me_free*sp["g2"]*sp["HCO3"]*sp["g1"]/(sp["a_h"])
    return np.log10(iap) - LOGK_MIN[mineral]

def sorb(sp, free, logK):
    """Competitive sorption on the carbonate site, Omar & Vilcaez Eq. 1.

    K_int = [>CO3Me+][H+] / ([>CO3H0][Me2+])  =>  [>CO3Me+] = K [>CO3H0] (Me) / (H)
    with the site balance  [>CO3]_T = [>CO3H0] + [>CO3-] + sum([>CO3Me+]).
    Returns moles sorbed per litre for each metal.
    """
    d = 1.0 + 10**LOGK_CO3H/sp["a_h"]                      # >CO3H0 and >CO3-
    for m, a in free.items():
        if logK.get(m) is None: continue
        d += 10**logK[m]*a*sp["g2"]/sp["a_h"]
    CO3H0 = S_T["CO3"]/d
    return {m: 10**logK[m]*free[m]*sp["g2"]/sp["a_h"]*CO3H0
            for m in free if logK.get(m) is not None}

def simulate(tot0, CT0, metals, logK, days=6.0, nstep=1440, sorption=True,
             precipitation=True, k_m=K_M):
    """Integrate the batch. Returns a DataFrame of concentration against time."""
    tot = dict(tot0); CT = CT0
    ppt = {m: 0.0 for m in metals}                 # moles per litre precipitated
    dt  = days*86400.0/nstep
    out = []
    for step in range(nstep + 1):
        sp   = speciate(tot, CT)
        free = {m: tot[m]*free_fraction(m, sp, tot) for m in metals}

        # --- record
        srb = sorb(sp, free, logK) if sorption else {m: 0.0 for m in metals}
        row = dict(t_day=step*dt/86400.0, pH=sp["pH"], CT=CT,
                   Ca=tot["Ca"], Mg=tot["Mg"], alk=sp["HCO3"] + 2*sp["CO3"])
        for m in metals:
            row[m] = max(tot[m] - srb.get(m, 0.0), 0.0)     # dissolved, after sorption
            row[m + "_sorbed"] = srb.get(m, 0.0)
            row[m + "_ppt"]    = ppt[m]
        out.append(row)
        if step == nstep: break

        # --- 1. kinetic dolomite dissolution (Lasaga 1984; Omar & Vilcaez Eq. 2)
        Q = (sp["HCO3"]*sp["g1"])**2*(tot["Ca"]*sp["g2"])*(tot["Mg"]*sp["g2"])/(sp["a_h"]**2)
        omega = Q/10**LOGK_MIN["Dolomite"]
        rate = S_AREA*k_m*sp["a_h"]*(1.0 - omega)           # mol L-1 s-1, may be negative
        dmol = rate*dt
        tot["Ca"] += dmol; tot["Mg"] += dmol; CT += 2*dmol

        # --- 2. equilibrium precipitation of any supersaturated carbonate
        if precipitation:
            sp = speciate(tot, CT)
            for mineral, m in MIN_CATION.items():
                if m not in tot or tot[m] <= 0: continue
                fr = free_fraction(m, sp, tot)
                si = mineral_SI(m, mineral, tot[m]*fr, sp)
                if si > 0:
                    # remove metal and carbonate until SI returns to zero
                    lo, hi = 0.0, min(tot[m], CT)*0.999
                    for _ in range(40):
                        mid = 0.5*(lo + hi)
                        t2 = dict(tot); t2[m] -= mid
                        s2 = speciate(t2, CT - mid)
                        if mineral_SI(m, mineral, t2[m]*free_fraction(m, s2, t2), s2) > 0:
                            lo = mid
                        else:
                            hi = mid
                    tot[m] -= hi; CT -= hi
                    if m in ppt: ppt[m] += hi
    return pd.DataFrame(out)

print("Model assembled:")
print("  kinetic dolomite dissolution -> equilibrium speciation -> equilibrium carbonate")
print("  precipitation -> competitive sorption on the carbonate site.")
print(f"  Surface area {S_AREA:.1f} m2/L, carbonate sites {S_T['CO3']*1e3:.3f} mmol/L, k_m = {K_M:.1e} mol m-2 s-1.")
print("  pH is an OUTPUT of the dissolution, not an input.")

# %% [markdown]
# ## 4 — Calibration against the produced-water experiment
#
# Omar & Vilcáez assign K_int for Sr, Cd and Pb as *"assumed values based on observed removal
# levels"*. The same procedure is applied here: for each metal, log K_int is adjusted until the
# simulated day-6 dissolved concentration matches the measured one. Ca and Mg keep Pokrovsky's
# measured values, and Sr, Cd and Pb keep the published Omar & Vilcáez values, so the only
# quantities determined here are those for **Co, Li and Ba**.

# %%
head(4, "Calibration against the produced-water experiment")

NACL = 40.0/58.44
def pw_initial():
    """Initial totals for the produced water, mol/L, from the day-0 row."""
    r = PW[(PW.batch == "pH6") & (PW.day == 0)].iloc[0]
    tot = {"Na": NACL, "Cl": NACL}
    tot["Ca"] = r.Ca_ppm/MM["Ca"]/1e3
    tot["Mg"] = r.Mg_ppm/MM["Mg"]/1e3
    for m in PW_METALS:
        tot[m] = r[m]/MM[m]/1e3
    # chloride balances the added salts
    tot["Cl"] = NACL + 2*(tot["Ca"] + tot["Mg"]) + sum(
        (1 if m == "Li" else 2)*tot[m] for m in PW_METALS)
    return tot

TOT0 = pw_initial()
CT0  = 1.0e-3            # mol/L initial dissolved inorganic carbon, from the day-0 pH of 6.32
MET  = ["Ca", "Mg"] + PW_METALS

def day6_measured(metal):
    return PW[(PW.batch == "pH6") & (PW.day == 6)][metal].iloc[0]

def predict_day6(metal, logK_metal, base=None):
    """Simulate with one metal's constant set to logK_metal; return day-6 dissolved mg/L."""
    lk = dict(LOGK_INT) if base is None else dict(base)
    lk[metal] = logK_metal
    df = simulate(TOT0, CT0, MET, lk, days=6.0, nstep=360)
    return df[metal].iloc[-1]*MM[metal]*1e3

def calibrate(metal, base, lo=-7.0, hi=2.0):
    """Adjust log K_int until the simulated day-6 concentration matches the measured one."""
    target = day6_measured(metal)
    f = lambda k: (predict_day6(metal, k, base) - target)**2
    res = minimize_scalar(f, bounds=(lo, hi), method="bounded",
                          options={"xatol": 0.02})
    return float(res.x), predict_day6(metal, float(res.x), base), target

base = dict(LOGK_INT)
rows = []
for metal in ["Co", "Li", "Ba"]:
    k, pred, meas = calibrate(metal, base)
    base[metal] = k
    c0 = PW[(PW.batch == "pH6") & (PW.day == 0)][metal].iloc[0]
    rows.append(dict(metal=metal, logK_int=k, predicted_day6_mgL=pred,
                     measured_day6_mgL=meas,
                     removal_pred=100*(1 - pred/c0), removal_meas=100*(1 - meas/c0)))
cal = pd.DataFrame(rows)
show(cal)
LOGK_ALL = dict(base)
print("\nFull constant set now in use (Omar & Vilcaez values kept, this study's added):")
show(pd.DataFrame([(m, v, "Pokrovsky 1999" if m in ("Ca","Mg") else
                    "Omar & Vilcaez 2024" if m in ("Sr","Cd","Pb") else "this study")
                   for m, v in LOGK_ALL.items()],
                  columns=["metal", "log K_int", "source"]))
